/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payroll.view;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import payroll.database.Koneksi;
/**
 *
 * @author Ryu
 */
public class FormAbsensi extends javax.swing.JFrame {
private DefaultTableModel model;

    private void aturLebarKolom() {
        javax.swing.table.TableColumnModel columnModel = tableAbsensi.getColumnModel();
        
        columnModel.getColumn(0).setPreferredWidth(40);
        columnModel.getColumn(1).setPreferredWidth(100);
        columnModel.getColumn(2).setPreferredWidth(100);
        columnModel.getColumn(3).setPreferredWidth(150);
        columnModel.getColumn(4).setPreferredWidth(80);
        columnModel.getColumn(5).setPreferredWidth(80);
        columnModel.getColumn(6).setPreferredWidth(150);
        
        tableAbsensi.getTableHeader().setResizingAllowed(true);
    }

    private void tampilData() {
        model = new DefaultTableModel() {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false;
            }
        };
        
        model.addColumn("No");
        model.addColumn("Tanggal");
        model.addColumn("NIK");
        model.addColumn("Nama");
        model.addColumn("Kode Jabatan");
        model.addColumn("Status");
        model.addColumn("Keterangan");
        
        tableAbsensi.setModel(model);

        try {
            String sql = "SELECT * FROM absensi ORDER BY id DESC";
            java.sql.Connection conn = (java.sql.Connection) payroll.database.Koneksi.configDB();
            java.sql.Statement st = conn.createStatement();
            java.sql.ResultSet rs = st.executeQuery(sql);
            
            int no = 1;
            while (rs.next()) {
                model.addRow(new Object[]{
                    no++,
                    rs.getString("tgl_absen"),
                    rs.getString("nik"),
                    rs.getString("nama_karyawan"),
                    rs.getString("kode_jabatan"),
                    rs.getString("status"),
                    rs.getString("keterangan")
                });
            }
            aturLebarKolom();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal load data: " + e.getMessage());
        }
    }
    
    private void kosongkanForm() {
        txtNIK.setText("");
        txtNama.setText("");
        txtJabatan.setText("");
        cmbStatus.setSelectedIndex(0);
        txtNIK.requestFocus();
    }
    /**
     * Creates new form FormAbsensi
     */
    public FormAbsensi() {
        initComponents();
        tampilData();
        aturLebarKolom();
        setLocationRelativeTo(null);
        java.time.LocalDate today = java.time.LocalDate.now();
        txtTanggal.setText(today.toString());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtTanggal = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNIK = new javax.swing.JTextField();
        btnCari = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtNama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtJabatan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        cmbStatus = new javax.swing.JComboBox<>();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableAbsensi = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        txtKeterangan = new javax.swing.JTextField();
        btnTutup = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Absensi Karyawan");

        jLabel1.setText("Tanggal (YYYY-MM-DD)");

        jLabel2.setText("NIK");

        btnCari.setText("Cari");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        jLabel3.setText("Nama Karyawan");

        txtNama.setEditable(false);

        jLabel4.setText("Kode Jabatan");

        txtJabatan.setEditable(false);

        jLabel5.setText("Status Kehadiran");

        cmbStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Hadir", "Sakit", "Izin", "Alpha" }));

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        tableAbsensi.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableAbsensi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableAbsensiMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableAbsensi);

        jLabel6.setText("Keterangan");

        txtKeterangan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtKeteranganActionPerformed(evt);
            }
        });

        btnTutup.setText("Tutup");

        btnHapus.setText("Hapus");
        btnHapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHapusMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(btnHapus)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTutup)
                .addGap(82, 82, 82))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtNIK, javax.swing.GroupLayout.DEFAULT_SIZE, 124, Short.MAX_VALUE)
                                        .addComponent(txtTanggal)
                                        .addComponent(txtNama))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(txtJabatan, javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(cmbStatus, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(btnSimpan)
                                    .addComponent(btnCari)))
                            .addComponent(txtKeterangan))
                        .addGap(0, 71, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtTanggal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNIK, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnCari))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cmbStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtKeterangan, javax.swing.GroupLayout.DEFAULT_SIZE, 45, Short.MAX_VALUE)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTutup, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
        try {
        String sql = "SELECT * FROM karyawan WHERE nik = ?";
        Connection conn = (Connection) Koneksi.configDB();
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, txtNIK.getText());
        ResultSet rs = pst.executeQuery();

        if (rs.next()) {
            txtNama.setText(rs.getString("nama_karyawan")); 
            txtJabatan.setText(rs.getString("kode_jabatan")); // Pastikan nama kolom db sesuai
        } else {
            JOptionPane.showMessageDialog(this, "NIK tidak ditemukan!");
            txtNama.setText("");
            txtJabatan.setText("");
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
                try {
        // 1. Validasi Input
        if (txtNIK.getText().isEmpty() || txtNama.getText().isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(this, "Harap cari data karyawan (NIK) terlebih dahulu!");
            return;
        }

        // 2. Siapkan Koneksi
        java.sql.Connection conn = (java.sql.Connection) payroll.database.Koneksi.configDB();

        // 3. LOGIKA CEK DUPLIKASI
        // "Coba cari di database, apakah NIK ini sudah ada datanya di Tanggal ini?"
        String sqlCek = "SELECT * FROM absensi WHERE nik = ? AND tgl_absen = ?";
        java.sql.PreparedStatement pstCek = conn.prepareStatement(sqlCek);
        pstCek.setString(1, txtNIK.getText());
        pstCek.setString(2, txtTanggal.getText());
        java.sql.ResultSet rs = pstCek.executeQuery();

        if (rs.next()) {
            // --- KONDISI A: DATA SUDAH ADA (Update) ---
            int jawab = javax.swing.JOptionPane.showConfirmDialog(this, 
                "Karyawan ini sudah absen pada tanggal " + txtTanggal.getText() + ".\nApakah Anda ingin mengubah (Update) data absennya?", 
                "Data Sudah Ada", 
                javax.swing.JOptionPane.YES_NO_OPTION);

            if (jawab == javax.swing.JOptionPane.YES_OPTION) {
                String sqlUpdate = "UPDATE absensi SET status=?, keterangan=?, kode_jabatan=?, nama_karyawan=? WHERE nik=? AND tgl_absen=?";
                java.sql.PreparedStatement pstUpdate = conn.prepareStatement(sqlUpdate);
                
                // Isi data baru
                pstUpdate.setString(1, cmbStatus.getSelectedItem().toString());
                pstUpdate.setString(2, txtKeterangan.getText());
                pstUpdate.setString(3, txtJabatan.getText());
                pstUpdate.setString(4, txtNama.getText());
                
                // Kunci pencarian (WHERE)
                pstUpdate.setString(5, txtNIK.getText());
                pstUpdate.setString(6, txtTanggal.getText());
                
                pstUpdate.executeUpdate();
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Diperbarui (Update)!");
            } else {
                return; // Jika pilih No, batalkan
            }

        } else {
            // --- KONDISI B: DATA BELUM ADA (Insert Baru) ---
            // (Ini adalah kode lama Anda)
            String sqlInsert = "INSERT INTO absensi (tgl_absen, nik, nama_karyawan, kode_jabatan, status, keterangan) VALUES (?, ?, ?, ?, ?, ?)";
            java.sql.PreparedStatement pstInsert = conn.prepareStatement(sqlInsert);

            pstInsert.setString(1, txtTanggal.getText());
            pstInsert.setString(2, txtNIK.getText());
            pstInsert.setString(3, txtNama.getText());
            pstInsert.setString(4, txtJabatan.getText());
            pstInsert.setString(5, cmbStatus.getSelectedItem().toString());
            pstInsert.setString(6, txtKeterangan.getText());

            pstInsert.execute();
            javax.swing.JOptionPane.showMessageDialog(this, "Absensi Baru Berhasil Disimpan!");
        }

        // 4. Refresh Tampilan
        tampilData();
        kosongkanForm();
        
    } catch (Exception e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Gagal Proses: " + e.getMessage());
        e.printStackTrace();
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void txtKeteranganActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtKeteranganActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtKeteranganActionPerformed

    private void btnHapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHapusMouseClicked
    if (txtNIK.getText().isEmpty() || txtTanggal.getText().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "Silakan klik data di tabel yang ingin dihapus!");
        return;
    }

    // Konfirmasi Hapus
    int confirm = javax.swing.JOptionPane.showConfirmDialog(this, 
            "Yakin ingin menghapus data absensi ini?", 
            "Konfirmasi Hapus", 
            javax.swing.JOptionPane.YES_NO_OPTION);

    if (confirm == javax.swing.JOptionPane.YES_OPTION) {
        try {
            // Query hapus berdasarkan NIK DAN TANGGAL (Agar data hari lain tidak ikut terhapus)
            String sql = "DELETE FROM absensi WHERE nik = ? AND tgl_absen = ?";
            
            java.sql.Connection conn = (java.sql.Connection) payroll.database.Koneksi.configDB();
            java.sql.PreparedStatement pst = conn.prepareStatement(sql);
            
            pst.setString(1, txtNIK.getText());
            pst.setString(2, txtTanggal.getText());
            
            int rowsAffected = pst.executeUpdate();
            
            if (rowsAffected > 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Data Berhasil Dihapus");
                tampilData();    // Refresh tabel
                kosongkanForm(); // Bersihkan textfield
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Gagal menghapus. Data mungkin sudah tidak ada.");
            }
            
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    }//GEN-LAST:event_btnHapusMouseClicked

    private void tableAbsensiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableAbsensiMouseClicked
    int baris = tableAbsensi.getSelectedRow();
    
    if (baris != -1) {
        // Kolom di model: 0=No, 1=Tanggal, 2=NIK, 3=Nama, 4=Jabatan, 5=Status, 6=Ket
        
        txtTanggal.setText(tableAbsensi.getValueAt(baris, 1).toString());
        txtNIK.setText(tableAbsensi.getValueAt(baris, 2).toString());
        txtNama.setText(tableAbsensi.getValueAt(baris, 3).toString());
        txtJabatan.setText(tableAbsensi.getValueAt(baris, 4).toString());
        cmbStatus.setSelectedItem(tableAbsensi.getValueAt(baris, 5).toString());
        txtKeterangan.setText(tableAbsensi.getValueAt(baris, 6).toString());
    }
    }//GEN-LAST:event_tableAbsensiMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormAbsensi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormAbsensi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnTutup;
    private javax.swing.JComboBox<String> cmbStatus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableAbsensi;
    private javax.swing.JTextField txtJabatan;
    private javax.swing.JTextField txtKeterangan;
    private javax.swing.JTextField txtNIK;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtTanggal;
    // End of variables declaration//GEN-END:variables
}
