/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package payroll.view;

/**
 *
 * @author Ryu
 */
public class MenuUtama extends javax.swing.JFrame {

    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        setAkses(false); 
    }
    
    public void setAkses(boolean loginStatus) {
        menuMaster.setEnabled(loginStatus);
        menuTransaksi.setEnabled(loginStatus);
        
        // Menu Login hanya aktif jika BELUM login
        menuLogin.setEnabled(!loginStatus); 
        
        //Menu Logout hanya aktif jika SUDAH login
        menuLogout.setEnabled(loginStatus); 
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        menuAplikasi = new javax.swing.JMenu();
        menuLogin = new javax.swing.JMenuItem();
        menuLogout = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        menuKeluar = new javax.swing.JMenuItem();
        menuMaster = new javax.swing.JMenu();
        menuJabatan = new javax.swing.JMenuItem();
        menuKaryawan = new javax.swing.JMenuItem();
        menuTransaksi = new javax.swing.JMenu();
        menuAbsensi = new javax.swing.JMenuItem();
        menuPenggajian = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Menu Utama");

        menuAplikasi.setText("Application");

        menuLogin.setText("Login");
        menuLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLoginActionPerformed(evt);
            }
        });
        menuAplikasi.add(menuLogin);

        menuLogout.setText("Logout");
        menuLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuLogoutActionPerformed(evt);
            }
        });
        menuAplikasi.add(menuLogout);
        menuAplikasi.add(jSeparator1);

        menuKeluar.setText("Close");
        menuKeluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKeluarActionPerformed(evt);
            }
        });
        menuAplikasi.add(menuKeluar);

        jMenuBar1.add(menuAplikasi);

        menuMaster.setText("Master Data");

        menuJabatan.setText("Position Data");
        menuJabatan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuJabatanActionPerformed(evt);
            }
        });
        menuMaster.add(menuJabatan);

        menuKaryawan.setText("Employee Data");
        menuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuKaryawanActionPerformed(evt);
            }
        });
        menuMaster.add(menuKaryawan);

        jMenuBar1.add(menuMaster);

        menuTransaksi.setText("Transaction");

        menuAbsensi.setText("Presence");
        menuAbsensi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuAbsensiActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuAbsensi);

        menuPenggajian.setText("Payroll");
        menuPenggajian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                menuPenggajianActionPerformed(evt);
            }
        });
        menuTransaksi.add(menuPenggajian);

        jMenuBar1.add(menuTransaksi);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuJabatanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuJabatanActionPerformed
        new FormDataJabatan().setVisible(true);
    }//GEN-LAST:event_menuJabatanActionPerformed

    private void menuPenggajianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuPenggajianActionPerformed
        new FormPenggajian().setVisible(true);
    }//GEN-LAST:event_menuPenggajianActionPerformed

    private void menuLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLogoutActionPerformed
        int tanya = javax.swing.JOptionPane.showConfirmDialog(null, "Yakin ingin Logout?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (tanya == javax.swing.JOptionPane.YES_OPTION) {
            new FormLogin().setVisible(true);
            this.dispose();
}
    }//GEN-LAST:event_menuLogoutActionPerformed

    private void menuKeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKeluarActionPerformed
        int tanya = javax.swing.JOptionPane.showConfirmDialog(null, "Yakin ingin keluar dari aplikasi?", "Konfirmasi", javax.swing.JOptionPane.YES_NO_OPTION);
        if (tanya == javax.swing.JOptionPane.YES_OPTION) {
            System.exit(0);
}
    }//GEN-LAST:event_menuKeluarActionPerformed

    private void menuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuKaryawanActionPerformed
        new FormDataJabatan ().setVisible(true);
    }//GEN-LAST:event_menuKaryawanActionPerformed

    private void menuAbsensiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuAbsensiActionPerformed
        new FormAbsensi ().setVisible(true);
    }//GEN-LAST:event_menuAbsensiActionPerformed

    private void menuLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuLoginActionPerformed
        FormLogin login = new FormLogin();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_menuLoginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JMenuItem menuAbsensi;
    private javax.swing.JMenu menuAplikasi;
    private javax.swing.JMenuItem menuJabatan;
    private javax.swing.JMenuItem menuKaryawan;
    private javax.swing.JMenuItem menuKeluar;
    private javax.swing.JMenuItem menuLogin;
    private javax.swing.JMenuItem menuLogout;
    private javax.swing.JMenu menuMaster;
    private javax.swing.JMenuItem menuPenggajian;
    private javax.swing.JMenu menuTransaksi;
    // End of variables declaration//GEN-END:variables
}
